### ISSUE TITLE
Start destination not added to backstack

### ISSUE THREAD

**Issue by laurentP22** [esentsov/dynamic-links-sample#1]
Hi,

When implementing your method to handle Firebase dynamic link on my project I realized the start direction wasn't added to the back stack.

Is it happening on this project too?

Thank you for this example, it's very clear and easy to understand!

**Comment by esentsov** [comment]
Hi, thanks for reporting that. Check out this PR fixing the issue #2.
If you are interested in the cause of such behavior please check [this link](https://developer.android.com/guide/navigation/navigation-deep-link#implicit) out.

**Comment by laurentP22** [comment]
Excelent ! Thank you very much !
